kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "angular-example-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/sibykarthikeyan/order-Management-UI"
  strategy:
    jenkinsPipelineStrategy:
      type: JenkinsPipeline
      jenkinsfile: pipeline{
        agent { label 'nodejs8' }
          stages{
            stage ('checkout'){
              steps{
                checkout scm
              }
            }
            stage ('install modules'){
              steps{
                sh '''
                  npm install --verbose -d 
                  npm install --save classlist.js
                '''
              }
            }
            stage ('test'){
              steps{
                sh '''
                  $(npm bin)/ng test --single-run --browsers Chrome_no_sandbox
                '''
              }
              post {
                  always {
                    junit "test-results.xml"
                  }
              }
            }
            stage ('code quality'){
              steps{
                sh '$(npm bin)/ng lint'
              }
            }
            stage ('build') {
              steps{
                sh '$(npm bin)/ng build --prod --build-optimizer'
              }
            }
            stage ('build image') {
              steps{
                sh '''
                  rm -rf node_modules
                  oc start-build angular-9-example --from-dir=. --follow
                '''
              }
            }
          }
        }    
